#Import numpy as np

import numpy as np

In [ ]:
#create array
#matrix
#arange, linspace,zeros,ones,eyes
#sqrt,unique,random

# how to import Numpy
import numpy as np

In [3]:
# create numpy array by converting lists

Vec= np.array([1,2,3,4,5,6,7,8,9,10,11])

In [4]:
print (Vec)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [5]:
#create a matrix

Matrix= np.array([[1,2,3], [4,5,6],[7,8,9]])

In [6]:
print (Matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#Transpose of matrix

print(Matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [8]:
x=np.sqrt(99900)

In [9]:
print(x)

316.06961258558215


In [10]:
#all about arrays

vec1=np.arange(0,300)

In [11]:
print(vec1)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [12]:
vec2=np.arange(2,50,10)
print(vec2)

[ 2 12 22 32 42]


In [13]:
#linspace:- linear spacing where both 1st and last is inclusive

vec3=np.linspace(0,20,10)
print(vec3)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


In [14]:
vec4=np.linspace(1,20,10)
print(vec4)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [15]:
#reshape
#it into matrix

vec3.reshape(5,2)

array([[ 0.        ,  2.22222222],
       [ 4.44444444,  6.66666667],
       [ 8.88888889, 11.11111111],
       [13.33333333, 15.55555556],
       [17.77777778, 20.        ]])

In [16]:
#zeros and ones

mat2=np.zeros([4,4])
print(mat2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
mat3=np.ones([5,5])
print(mat3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
mat4=np.zeros([1,4])
print(mat4)

[[0. 0. 0. 0.]]


In [19]:
#identify matrix

mat5=np.eye(6)
print(mat5)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [20]:
mat8=mat5
print(mat8.T)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [21]:
#vectors can be added nd substracted of same size

vec1=np.arange(1,6)
print(vec1)

[1 2 3 4 5]


In [22]:
vec2=np.arange(5,10)
print(vec2)

[5 6 7 8 9]


In [23]:
vec1+vec2

array([ 6,  8, 10, 12, 14])

In [24]:
vec1-vec2

array([-4, -4, -4, -4, -4])

In [25]:
vec1*vec2

array([ 5, 12, 21, 32, 45])

In [26]:
vec1/vec2

array([0.2       , 0.33333333, 0.42857143, 0.5       , 0.55555556])

In [27]:
1/vec1

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [28]:
print(np.sqrt(vec1))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [29]:
#unique value in an array

vec7=np.array(["orange","red","1","purple","raksha","orange","rice"])
print(vec7)

['orange' 'red' '1' 'purple' 'raksha' 'orange' 'rice']


In [30]:
print(np.unique(vec7))

['1' 'orange' 'purple' 'raksha' 'red' 'rice']


In [31]:
#genrate random variable

#unique random variable
rand_mat=np.random.rand(10,10)
print(rand_mat)


[[0.08378261 0.72898885 0.769099   0.68606521 0.20292182 0.7222715
  0.18520199 0.05734274 0.58260877 0.96381882]
 [0.0854407  0.31700474 0.76352071 0.90041833 0.16088808 0.36057194
  0.96079087 0.40984058 0.12242029 0.15589774]
 [0.10851832 0.68138078 0.46638963 0.16066422 0.44617513 0.54351667
  0.20288085 0.03191815 0.31762785 0.55164654]
 [0.43155149 0.06259876 0.538311   0.43749997 0.19898796 0.84651158
  0.94560387 0.83556463 0.66655194 0.38507835]
 [0.84964012 0.54974747 0.71657037 0.56906102 0.41264248 0.79750356
  0.34031072 0.22455086 0.65535383 0.69348128]
 [0.83751821 0.6770664  0.42099613 0.28903749 0.33640834 0.05864173
  0.52378848 0.82945436 0.51706927 0.82332448]
 [0.90581902 0.21996376 0.8755276  0.7115291  0.35976894 0.63856018
  0.56192499 0.64500433 0.62481749 0.81631096]
 [0.35794701 0.68264495 0.0383556  0.03490169 0.33400385 0.02617161
  0.64422312 0.56676008 0.61751611 0.40615026]
 [0.91222926 0.63587881 0.48446914 0.30470833 0.43847579 0.44380127
  0.022205   

In [32]:
#mean

z=np.mean(rand_mat)
print(z)

0.48393519741143093


In [33]:
#max

np.max(rand_mat)


0.9638188194292322

In [34]:
#min

np.min(rand_mat)

0.022204996319024284

In [35]:
#logical entries
#randn is for freezing any 20 integers values

rand_vec=np.random.randn(20)
print (rand_vec)

[-0.88468923 -1.24198236  0.14134247 -2.2200909   0.00710487  0.49147207
  0.11296505 -0.38448716 -0.90022015  1.78562098  0.29456024  1.33967866
  0.37279041 -0.53117349  0.15121402 -1.35824975  0.29427667 -0.77055586
  1.08131765  0.29804468]
